import Header from '@components/Header'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={"relative h-[2000px]"}>
      <Head>
        <title >Home Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>

      <main>
        
      </main>

      
    </div>
  )
}
