import requests from "../utils/requests";
import { GetServerSideProps } from "next";
import { useRecoilValue } from "recoil";

// Component
import Head from "next/head";
import Header from "@components/Header";
import Banner from "@components/Banner";
import Row from "@components/Row";
import Modal from "@components/Modal";

// Types
import { TAnime } from "../types/movie.type";

// Hooks
import useAuth from "hooks/useAuth";
import { modalState } from "atoms/modalAtom";

import { useQuery } from "@apollo/client";
import { GET_ANIME_LIST } from "../queries/GET_ANIME_LIST";

type Props = {}

const Home = (props: Props) => {

  const { loading } = useAuth();
  const showModal = useRecoilValue(modalState);

  // Start of  client gql
  const { data: data_trending } = useQuery(GET_ANIME_LIST, {
    variables: variable_trending,
  });

  const { data: data_season } = useQuery(GET_ANIME_LIST, {
    variables: variable_summer22,
  });

  const { data: data_popular} = useQuery(GET_ANIME_LIST, {
    variables: variable_mostly_popular,
  });

  const { data: data_best } = useQuery(GET_ANIME_LIST, {
    variables: variable_best_anime,
  });

  // end of gql

  return (
    <div className={"relative md:h-[140vh] bg-gradient-to-b"}>
      <Head>
        <title>Home AnimeList</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className="relative pb-24 pl-4 lg:space-y-24 lg:pl-16">
        <Banner movies={data_trending?.Page?.media} />
        <section className=" md:space-y-24">
          <Row title="Trending Now" movies={data_trending?.Page?.media} />
          <Row title="Summer 2022" movies={data_season?.Page?.media} />
          <Row title="Popular Animes" movies={data_popular?.Page?.media} />
          <Row title="Best Anime" movies={data_best?.Page?.media} />
        </section>
      </main>

      {showModal && <Modal />}
    </div>
  );
};

const variable_trending = {
  page: 1,
  type: "ANIME",
  sort: ["TRENDING_DESC", "POPULARITY_DESC"],
};

const variable_summer22 = {
  page: 1,
  type: "ANIME",
  seasonYear: 2022,
  season: "SUMMER",
};

const variable_mostly_popular = {
  page: 1,
  type: "ANIME",
  sort: ["POPULARITY_DESC"],
};

const variable_best_anime = {
  page: 1,
  type: "ANIME",
  sort: ["SCORE_DESC"],
};

export default Home;
